### ISSUE TITLE
Broken layout in IE11

### ISSUE THREAD

**Issue by larsnystrom** [wojtekmaj/react-calendar#42]
The layout is broken in IE11:

<img width="439" alt="skarmavbild 2018-03-05 kl 12 11 30" src="https://user-images.githubusercontent.com/1000370/36972205-94f6beb0-206e-11e8-8315-672cfc43431c.png">

Compared to Chrome:
<img width="371" alt="skarmavbild 2018-03-05 kl 12 12 48" src="https://user-images.githubusercontent.com/1000370/36972206-95156446-206e-11e8-81e8-648e3909418c.png">

Right now I'm unsure if (1) the problem is on my end, or (2) if it's because of the quirky flexbox implementation in IE11, or (3) if you're not supporting IE?

Can I remove the standard stylesheet somehow so I can style it myself?

**Comment by wojtekmaj** [comment]
Hello,
I do support IE11. This might be a bug on our or your side. I'm unable to test it at the moment. I see you're using custom styles, maybe you're missing something like container width?

**Comment by larsnystrom** [comment]
The only style I've added is:

```css
.panel-body > .react-calendar {
    border: 0;
    width: 100%;
}
```

That is to make react-calendar expand to use the entire width of the panel-body (I'm using bootstrap 3) and also to remove the default border.

**Comment by PiTomar** [comment]
Hello,
I’ve implemented the calendar today in a new project an observed the same behaviour.
In Chrome everything is ok but in IE11 the date-items flow over the calendar borders.
Maybe some bug with the percentage calculation of the flex-basis? 

E.g. the Buttons for the day-items have a style "flex-basis: 14.2...%;"
In Chrome this is displayed about 20px and in IE 66px.

Chrome:
![chrome](https://user-images.githubusercontent.com/37152440/37105087-98247804-222e-11e8-8655-eb4d9a9dd258.png)
IE:
![ie](https://user-images.githubusercontent.com/37152440/37105091-9b2b12a6-222e-11e8-9db6-51f418df523c.png)

**Comment by wojtekmaj** [comment]
Hello,
I've been facing some environment issues after switching machines, I'll look into this ASAP.

**Comment by wojtekmaj** [comment]
Thank you for your patience. The issue has been fixed and will be public in incoming version v2.13.2.

**Comment by PiTomar** [comment]
Thanks for your fast response.
Now the Items are in the calendar but on my test environment still not on the right place. The day-items seems to big so the new-line-break is at the wrong place. (3 and 4 should be under Saturday/ Sunday)
![unbenannt](https://user-images.githubusercontent.com/37152440/37140304-8e34ccd0-22b1-11e8-8ff8-658bd457259c.png)

**Comment by lisahoong** [comment]
I am experiencing a similar issue with mobile view in chrome
![image](https://user-images.githubusercontent.com/23561646/37298727-7f02a1da-25f7-11e8-9930-5eb9e351a390.png)

**Comment by nathan-haines** [comment]
@PiTomar did you ever determine how to fix this? Running into the same issue

**Comment by PiTomar** [comment]
@nathan-haines Please see issue [#45 "Broken layout in Safari mobile"](https://github.com/wojtekmaj/react-calendar/issues/45#issuecomment-373231218). There we currently also discus the IE11 positioning issue.
As temporary workaround, you can try to remove some margins/ paddings of the '.react-calendar button' items.
